---
- name: filebeat playbook
  hosts: webservers
  become: true
  tasks:

  - name: Download filebeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

  - name: Install filebeat .deb file
    command: dpkg -i filebeat-7.6.1-amd64.deb

  - name: Copy filebeat config
    copy: 
      src: /etc/ansible/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable filebeat system module
    command: filebeat modules enable system

  - name: setup filebeat
    command: filebeat setup

  - name: Start filebeat service
    command: service filebeat start

  - name: enable filebeat service on boot
    systemd: 
      name: filebeat
      enabled: yes

